eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8764/eureka/
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
      endpoint1:
        uri: http://PAYMENT-SERVICE/payment/doPayment

